# Theme and Plugins
remote_theme: pages-themes/modernist@v0.2.0
plugins:
  - jekyll-remote-theme  # Required for GitHub Pages to load the Modernist theme

# Site Information
title: Michael Laudano
description: EPortfolio

# Markdown Configuration
markdown: kramdown
kramdown:
  parse_block_html: true

# Navigation Links
# These links will appear at the top of your site under the title and description.
nav:
  - name: Home
    link: /
  - name: Software Design and Engineering
    link: /software-design-engineering/
  - name: About
    link: /about/
  - name: Contact
    link: /contact/

include:
  - "*.java"
  - "*.py"
  - "*.html"
  - "*.css"
  - "*.js"
  - "*.sql"
